sonar.organization=cogleighton-edd
sonar.projectKey=cogleighton-edd_sas-to-pyspark-migration
sonar.projectName=sas-to-pyspark-migration

sonar.sources=pyspark,tools
sonar.tests=tests
sonar.python.version=3.11

sonar.host.url=https://sonarcloud.io
